# Generated by Django 5.2.6 on 2025-09-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacionExterna',
            fields=[
                ('idOrganizacion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('representanteLegal', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('ubicacion', models.CharField(max_length=100)),
                ('sectorEconomico', models.CharField(max_length=100)),
                ('actividadPrincipal', models.CharField(max_length=100)),
            ],
        ),
    ]
