# Generated by Django 5.2.5 on 2025-09-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacionexterna',
            options={'verbose_name': 'organizacion_externa', 'verbose_name_plural': 'organizaciones_externas'},
        ),
        migrations.AlterModelTable(
            name='organizacionexterna',
            table='organizaciones_externas',
        ),
    ]
