# Generated by Django 5.2.6 on 2025-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0002_alter_organizacionexterna_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacionexterna',
            name='nit',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
