# Generated by Django 5.2.6 on 2025-09-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0003_organizacionexterna_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionexterna',
            name='nit',
            field=models.CharField(max_length=12),
        ),
    ]
