# Generated by Django 5.2.6 on 2025-09-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0004_alter_organizacionexterna_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionexterna',
            name='nit',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
