# Generated by Django 5.2.6 on 2025-09-24 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0005_alter_organizacionexterna_nit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacionexterna',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
