# Generated by Django 5.2.6 on 2025-09-27 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0006_organizacionexterna_creador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionexterna',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
