# Generated by Django 5.2.5 on 2025-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0007_alter_organizacionexterna_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionexterna',
            name='actividadPrincipal',
            field=models.CharField(max_length=200),
        ),
    ]
