# Generated by Django 5.2.6 on 2025-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0008_alter_organizacionexterna_actividadprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionexterna',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
