# Generated by Django 5.2.5 on 2025-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0009_alter_organizacionexterna_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionexterna',
            name='sectorEconomico',
            field=models.CharField(choices=[('educacion y ciencia', 'Educación y Ciencia'), ('tecnologia y comunicaciones', 'Tecnología y Comunicaciones'), ('salud y bienestar', 'Salud y Bienestar'), ('empresarial e industrial', 'Empresarial e Industrial'), ('finanzas y servicios profesionales', 'Finanzas y Servicios Profesionales'), ('cultura y medios', 'Cultura y Medios'), ('medio ambiente y sostenibilidad', 'Medio Ambiente y Sostenibilidad'), ('gobierno y organismos publicos', 'Gobierno y Organismos Públicos'), ('organizaciones sociales y ONGs', 'Organizaciones Sociales y ONGs'), ('turismo, hoteleria y gastronomia', 'Turismo, Hotelería y Gastronomía'), ('comercio y consumo', 'Comercio y Consumo'), ('otro', 'Otro')], max_length=100),
        ),
    ]
