# Generated by Django 5.2.5 on 2025-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0010_alter_organizacionexterna_sectoreconomico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacionexterna',
            name='sectorEconomico',
            field=models.CharField(choices=[('Educacion y Ciencia', 'Educación y Ciencia'), ('Tecnologia y Comunicaciones', 'Tecnología y Comunicaciones'), ('Salud y Bienestar', 'Salud y Bienestar'), ('Empresarial e Industrial', 'Empresarial e Industrial'), ('Finanzas y Servicios profesionales', 'Finanzas y Servicios Profesionales'), ('Cultura y Medios', 'Cultura y Medios'), ('Medio Ambiente y Sostenibilidad', 'Medio Ambiente y Sostenibilidad'), ('Gobierno y Organismos publicos', 'Gobierno y Organismos Públicos'), ('Organizaciones sociales y ONGs', 'Organizaciones Sociales y ONGs'), ('Turismo, Hoteleria y Gastronomia', 'Turismo, Hotelería y Gastronomía'), ('Comercio y Consumo', 'Comercio y Consumo'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
