# Generated by Django 5.2.5 on 2025-11-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_organizations', '0011_alter_organizacionexterna_sectoreconomico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizacionexterna',
            old_name='actividadPrincipal',
            new_name='actividad_principal',
        ),
        migrations.RenameField(
            model_name='organizacionexterna',
            old_name='idOrganizacion',
            new_name='id_organizacion',
        ),
        migrations.RenameField(
            model_name='organizacionexterna',
            old_name='representanteLegal',
            new_name='representante_legal',
        ),
        migrations.RenameField(
            model_name='organizacionexterna',
            old_name='sectorEconomico',
            new_name='sector_economico',
        ),
    ]
