# Generated by Django 5.2.6 on 2025-09-27 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviado', 'Enviado'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Borrador', max_length=10)),
                ('tipo', models.CharField(choices=[('Ludico', 'Lúdico'), ('Academico', 'Académico')], max_length=100)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'db_table': 'eventos',
            },
        ),
    ]
