# Generated by Django 5.2.6 on 2025-09-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instalacionfisica'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacionesAsignadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evento')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instalacionfisica')),
            ],
            options={
                'verbose_name': 'instalacion_asignada',
                'verbose_name_plural': 'instalaciones_asignadas',
                'db_table': 'instalaciones_asignadas',
                'constraints': [models.UniqueConstraint(fields=('evento', 'instalacion'), name='unique_evento_instalacion')],
            },
        ),
    ]
