# Generated by Django 5.2.6 on 2025-10-02 03:32

import apps.events.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_instalacionesasignadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadoresEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aval', models.FileField(upload_to=apps.events.utils.path_coordinador_aval)),
                ('tipo', models.CharField(max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evento')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coordinador_evento',
                'verbose_name_plural': 'coordinadores_eventos',
                'db_table': 'coordinadores_eventos',
                'constraints': [models.UniqueConstraint(fields=('evento', 'organizador'), name='unique_evento_organizador')],
            },
        ),
    ]
