# Generated by Django 5.2.6 on 2025-10-02 03:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_coordinadoreseventos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoordinadoresEventos',
            new_name='OrganizadoresEventos',
        ),
        migrations.AlterModelOptions(
            name='organizadoreseventos',
            options={'verbose_name': 'organizador_evento', 'verbose_name_plural': 'organizadores_eventos'},
        ),
        migrations.AlterModelTable(
            name='organizadoreseventos',
            table='organizadores_eventos',
        ),
    ]
