# Generated by Django 5.2.6 on 2025-10-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_coordinadoreseventos_organizadoreseventos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizadoreseventos',
            name='tipo',
            field=models.CharField(choices=[('director_programa', 'Director del Programa'), ('director_docencia', 'Director de Docencia')], max_length=50),
        ),
    ]
