# Generated by Django 5.2.5 on 2025-10-04 14:49

import apps.events.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instalacionfisica'),
        ('events', '0005_alter_organizadoreseventos_tipo'),
        ('external_organizations', '0008_alter_organizacionexterna_actividadprincipal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacionesasignadas',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones_asignadas', to='events.evento'),
        ),
        migrations.AlterField(
            model_name='instalacionesasignadas',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to='core.instalacionfisica'),
        ),
        migrations.AlterField(
            model_name='organizadoreseventos',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizadores_asignados', to='events.evento'),
        ),
        migrations.AlterField(
            model_name='organizadoreseventos',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizacionesInvitadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_asiste', models.BooleanField(default=False, verbose_name='¿Representante legal asiste?')),
                ('representante_alterno', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_participacion', models.FileField(upload_to=apps.events.utils.path_organizacion_certificado)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones_invitadas', to='events.evento')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_invitados', to='external_organizations.organizacionexterna')),
            ],
            options={
                'verbose_name': 'organizacion_invitada',
                'verbose_name_plural': 'organizaciones_invitadas',
                'db_table': 'organizaciones_invitadas',
                'constraints': [models.UniqueConstraint(fields=('evento', 'organizacion'), name='unique_evento_organizacion')],
            },
        ),
    ]
