# Generated by Django 5.2.5 on 2025-10-05 01:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_idusuario_facultad_idfacultad'),
        ('events', '0006_alter_instalacionesasignadas_evento_and_more'),
        ('external_organizations', '0008_alter_organizacionexterna_actividadprincipal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstalacionesAsignadas',
            new_name='InstalacionAsignada',
        ),
        migrations.RenameModel(
            old_name='OrganizacionesInvitadas',
            new_name='OrganizacionInvitada',
        ),
        migrations.RenameModel(
            old_name='OrganizadoresEventos',
            new_name='OrganizadorEvento',
        ),
    ]
