# Generated by Django 5.2.5 on 2025-10-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_instalacionesasignadas_instalacionasignada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
