# Generated by Django 5.2.6 on 2025-10-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_instalacionesasignadas_instalacionasignada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fechaEnvio',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
