# Generated by Django 5.2.5 on 2025-10-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_evento_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_creacion',
            new_name='fecha_ultimo_cambio',
        ),
    ]
