# Generated by Django 5.2.5 on 2025-10-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_fecha_creacion_evento_fecha_ultimo_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fechaEnvio',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
