# Generated by Django 5.2.5 on 2025-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_evento_fechaenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='capacidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
