# Generated by Django 5.2.5 on 2025-11-04 01:28

import apps.events.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_evento_capacidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEvento',
            fields=[
                ('idEvaluacion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fechaEvaluacion', models.DateField(auto_now_add=True)),
                ('tipoEvaluacion', models.CharField(choices=[('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo')], max_length=10)),
                ('justificacion', models.TextField()),
                ('acta', models.FileField(upload_to=apps.events.utils.path_acta)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='events.evento')),
            ],
        ),
    ]
