# Generated by Django 5.2.5 on 2025-11-04 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_evaluacionevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionevento',
            name='justificacion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
