# Generated by Django 5.2.6 on 2025-11-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_evaluacionevento_justificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionevento',
            name='notificacionLeida',
            field=models.BooleanField(default=False),
        ),
    ]
