# Generated by Django 5.2.6 on 2025-11-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_evaluacionevento_notificacionleida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionevento',
            name='fechaEvaluacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
