# Generated by Django 5.2.6 on 2025-11-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_evaluacionevento_fechaevaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionevento',
            options={'verbose_name': 'evaluacion_evento', 'verbose_name_plural': 'evaluaciones_eventos'},
        ),
        migrations.AlterModelTable(
            name='evaluacionevento',
            table='evaluaciones_eventos',
        ),
    ]
