# Generated by Django 5.2.6 on 2025-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_evaluacionevento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='notificacionLeida',
            field=models.BooleanField(default=False),
        ),
    ]
