# Generated by Django 5.2.5 on 2025-11-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_evento_notificacionleida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='notificacionLeida',
            new_name='notificacionEnvioLeida',
        ),
    ]
