# Generated by Django 5.2.6 on 2025-11-13 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_rename_notificacionleida_evento_notificacionenvioleida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha',
            new_name='fechaInicio',
        ),
        migrations.AddField(
            model_name='evento',
            name='fechaFin',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
