# Generated by Django 5.2.5 on 2025-11-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_rename_fecha_evento_fechainicio_evento_fechafin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionevento',
            old_name='fechaEvaluacion',
            new_name='fecha_evaluacion',
        ),
        migrations.RenameField(
            model_name='evaluacionevento',
            old_name='idEvaluacion',
            new_name='id_evaluacion',
        ),
        migrations.RenameField(
            model_name='evaluacionevento',
            old_name='notificacionLeida',
            new_name='notificacion_leida',
        ),
        migrations.RenameField(
            model_name='evaluacionevento',
            old_name='tipoEvaluacion',
            new_name='tipo_evaluacion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fechaEnvio',
            new_name='fecha_envio',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='horaFin',
            new_name='hora_fin',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='horaInicio',
            new_name='hora_inicio',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='idEvento',
            new_name='id_evento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='notificacionEnvioLeida',
            new_name='notificacion_envio_leida',
        ),
    ]
