from django.conf import settings
from django.db import IntegrityError
from django.contrib.auth.hashers import check_password
from django.db.models import Q, Value, Case, When, CharField
from django.db.models.functions import Concat
import re

from apps.users.email_service import send_email
from .models import *

# Password history limit
PASSWORD_HISTORY_LIMIT = 3

def validate_new_password(user, new_password):
    """
    Validates that the new password is not the same as the current one or the last N used by the user.
    """

    if not re.match(r'^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$', new_password):
        raise ValueError("La nueva contraseña debe tener al menos 8 caracteres, incluyendo letras y números.")

    if not new_password:
        raise ValueError("La nueva contraseña es requerida.")

    # Compare with the current one
    if check_password(new_password, user.password):
        raise ValueError("No puede ser igual a la actual.")

    # Compare with the last N passwords
    historial = (
        Contrasenia.objects
        .filter(id_usuario=user)
        .order_by('-fecha_cambio')[:PASSWORD_HISTORY_LIMIT]
    )
    for h in historial:
        if check_password(new_password, h.clave):
            raise ValueError("Esta contraseña ya ha sido utilizada anteriormente.")

    return True


def save_password_history(user):
    
    # Register new password (current hash)
    Contrasenia.objects.create(id_usuario=user, clave=user.password, es_activa=True)

    # Keep only the last N
    ids_a_conservar = list(
        Contrasenia.objects
        .filter(id_usuario=user)
        .order_by('-fecha_cambio')
        .values_list('id_contrasenia', flat=True)[:PASSWORD_HISTORY_LIMIT]
    )
    if ids_a_conservar:
        Contrasenia.objects.filter(id_usuario=user).exclude(id_contrasenia__in=ids_a_conservar).delete()


class UserService:
    @staticmethod
    def registrar(data):
        rol = data.get("rol")

        try:
            usuario = Usuario.objects.create_user(
                email=data["email"],
                password=data["password"],
                nombres=data["nombres"],
                apellidos=data["apellidos"],
                telefono=data["telefono"],
                numero_identificacion=data["numero_identificacion"],
            )
        except IntegrityError as e:
            s = str(e).lower()
            if "email" in s:
                raise ValueError("El correo electrónico ya está registrado.") from e
            if "numeroidentificacion" in s:
                raise ValueError("El documento de identidad ya está registrado.") from e
            if "telefono" in s or "phone" in s:
                raise ValueError("El teléfono ya está registrado.") from e
            raise ValueError("Datos duplicados en el usuario.") from e
        
        # --- Guardar la contraseña inicial en el historial ---
        Contrasenia.objects.create(
            id_usuario=usuario,
            clave=usuario.password,  # hash generated by set_password
            es_activa=True,
        )

        # --- Crear el registro según el rol; si falla, limpiar al usuario ---
        try:
            if rol == "estudiante":
                programa = Programa.objects.get(pk=data["programa_id"])
                Estudiante.objects.create(usuario=usuario, codigo_estudiante=data["codigo_estudiante"], programa=programa)

            elif rol == "docente":
                unidad = UnidadAcademica.objects.get(pk=data["unidad_academica_id"])
                Docente.objects.create(usuario=usuario, unidad_academica=unidad)

            elif rol == "secretaria":
                facultad = Facultad.objects.get(pk=data["facultad_id"])
                # Ensure only one secretaria per facultad
                if Secretaria.objects.filter(facultad=facultad).exists():
                    if getattr(usuario, 'id_usuario', None):
                        usuario.delete()
                    raise ValueError("Ya existe una secretaria registrada para esta facultad.")
                Secretaria.objects.create(usuario=usuario, facultad=facultad)
                
            send_email(
                    subject="Bienvenido/a a SIGEU 🎓",
                    to_email=usuario.email,
                    template_name="users/successful_register/correo_registro.html",
                    context={
                        "nombre": usuario.nombres,
                        "email": usuario.email,
                        "rol": rol,
                        "login_url": "http://localhost:8000/users/inicio-sesion/",
                        "soporte_email": settings.DEFAULT_FROM_EMAIL,
                    },
                    text_body=f"Hola {usuario.nombres}, tu registro como {rol} en SIGEU ha sido exitoso.",
                )

        except (Programa.DoesNotExist, UnidadAcademica.DoesNotExist, Facultad.DoesNotExist) as e:
            if getattr(usuario, 'id_usuario', None):
                usuario.delete()
            raise ValueError("ID relacionado inválido para el rol seleccionado.") from e

        except IntegrityError as e:
            if getattr(usuario, 'id_usuario', None):
                usuario.delete()
            s = str(e).lower()
            if "codigo_estudiante" in s or "codigo" in s:
                raise ValueError("El código de estudiante ya existe.") from e
            if "unique_secretaria_por_facultad" in s or ("facultad" in s and "unique" in s):
                raise ValueError("Ya existe una secretaria registrada para esta facultad.") from e
            raise ValueError("Datos duplicados para el registro del rol.") from e

        except Exception as e:
            if getattr(usuario, 'id_usuario', None):
                usuario.delete()
            raise

        return usuario.id_usuario

    @staticmethod
    def cambiar_password(user, new_password):
        """
        Changes the user's password validating against history.
        """
        validate_new_password(user, new_password)
        user.set_password(new_password)
        user.save()
        save_password_history(user)
        return True
    

    @staticmethod
    def listar_organizadores():
        return Usuario.objects.filter(
            Q(docente__isnull=False) | Q(estudiante__isnull=False)
        ).annotate(
            nombre_completo=Concat('nombres', Value(' '), 'apellidos'),
            rol=Case(
                When(estudiante__isnull=False, then=Value('Estudiante')),
                When(docente__isnull=False, then=Value('Docente')),
                default=Value('Usuario'),
                output_field=CharField()
            )
        ).values("id_usuario", "nombre_completo", "numero_identificacion", "rol")

    @staticmethod
    def filtrar_organizadores_por_nombre_completo(nombre_completo, usuario_actual_id=None):
        if not nombre_completo:
         return []
        
        qs = (
            Usuario.objects
            .filter(Q(docente__isnull=False) | Q(estudiante__isnull=False))  # Solo organizadores
            .annotate(
                nombre_completo=Concat('nombres', Value(' '), 'apellidos'), # Añadir propiedad nombre completo
                rol=Case(                                                   # Añadir propiedad rol
                    When(estudiante__isnull=False, then=Value('Estudiante')),
                    When(docente__isnull=False, then=Value('Docente')),
                    default=Value('Usuario'),
                    output_field=CharField()
                )
            )
            .filter(nombre_completo__icontains=nombre_completo)
            .values("id_usuario", "nombre_completo", "numero_identificacion", "rol")
        )

        if usuario_actual_id:
            qs = qs.exclude(id_usuario=usuario_actual_id)

        return list(qs.values("id_usuario", "nombre_completo", "numero_identificacion", "rol"))
    
    # * This method allows you to obtain a user as an instance of the model.
    @staticmethod
    def obtener_instance_por_id(id_usuario):
        try:
            usuario = Usuario.objects.get(id_usuario=id_usuario)
            return usuario
        except Usuario.DoesNotExist:
            return False

    # * This method allows you to obtain a user as an object because it includes the role
    @staticmethod
    def obtener_organizador_por_id(id_usuario):
        try:
            usuario = (
                Usuario.objects
                .filter(Q(estudiante__isnull=False) | Q(docente__isnull=False))  # solo organizadores
                .annotate(
                    rol=Case(
                        When(estudiante__isnull=False, then=Value('Estudiante')),
                        When(docente__isnull=False, then=Value('Docente')),
                        default=Value('Usuario'),
                        output_field=CharField()
                    )
                )
                .values("id_usuario", "numero_identificacion", "nombres", "apellidos", "email", "telefono", "rol")
                .get(id_usuario=id_usuario)
            )

            return usuario
        except Usuario.DoesNotExist:
            return False  

    @staticmethod
    def obtener_usuario_por_email(email):
        try:
            usuario = Usuario.objects.get(email=email)
            return usuario
        except Usuario.DoesNotExist:
            return False