# Generated by Django 5.2.6 on 2025-09-28 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('idUsuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'facultad',
                'verbose_name_plural': 'facultades',
                'db_table': 'facultades',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('idPrograma', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='core.facultad')),
            ],
            options={
                'db_table': 'programas',
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('idUnidadAcademica', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_academicas', to='core.facultad')),
            ],
            options={
                'verbose_name': 'unidad_academica',
                'verbose_name_plural': 'unidades_academicas',
                'db_table': 'unidades_academicas',
            },
        ),
    ]
