# Generated by Django 5.2.6 on 2025-09-28 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalacionFisica',
            fields=[
                ('idInstalacion', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo', models.CharField(choices=[('Salon', 'Salón'), ('Auditorio', 'Auditorio'), ('Laboratorio', 'Laboratorio'), ('Cancha', 'Cancha')], max_length=11)),
            ],
            options={
                'verbose_name': 'instalacion_fisica',
                'verbose_name_plural': 'instalaciones_fisicas',
                'db_table': 'instalaciones_fisicas',
            },
        ),
    ]
