# Generated by Django 5.2.5 on 2025-10-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instalacionfisica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultad',
            old_name='idUsuario',
            new_name='idFacultad',
        ),
    ]
