# Generated by Django 5.2.5 on 2025-11-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_idusuario_facultad_idfacultad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultad',
            old_name='idFacultad',
            new_name='id_facultad',
        ),
        migrations.RenameField(
            model_name='instalacionfisica',
            old_name='idInstalacion',
            new_name='id_instalacion',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='idPrograma',
            new_name='id_programa',
        ),
        migrations.RenameField(
            model_name='unidadacademica',
            old_name='idUnidadAcademica',
            new_name='id_unidad_academica',
        ),
    ]
