# Generated by Django 5.2.5 on 2025-09-19 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('numeroIdentificacion', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('idUsuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'facultad',
                'verbose_name_plural': 'facultades',
                'db_table': 'authentication_facultad',
            },
        ),
        migrations.CreateModel(
            name='Contrasenia',
            fields=[
                ('idContrasenia', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCambio', models.DateTimeField(auto_now_add=True)),
                ('clave', models.CharField(max_length=128)),
                ('es_activa', models.BooleanField(default=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrasenias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('idPrograma', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='users.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('idUnidadAcademica', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_academicas', to='users.facultad')),
            ],
            options={
                'verbose_name': 'unidad_academica',
                'verbose_name_plural': 'unidades_academicas',
                'db_table': 'authentication_unidad_academica',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='docente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unidadAcademica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='users.unidadacademica')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo_estudiante', models.CharField(max_length=7, unique=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='users.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secretaria', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretarias', to='users.facultad')),
            ],
        ),
    ]
