# Generated by Django 5.2.5 on 2025-09-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contrasenia',
            table='contrasenias',
        ),
        migrations.AlterModelTable(
            name='docente',
            table='docentes',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiantes',
        ),
        migrations.AlterModelTable(
            name='facultad',
            table='facultades',
        ),
        migrations.AlterModelTable(
            name='programa',
            table='programas',
        ),
        migrations.AlterModelTable(
            name='secretaria',
            table='secretarias',
        ),
        migrations.AlterModelTable(
            name='unidadacademica',
            table='unidades_academicas',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
