# Generated by Django 5.2.6 on 2025-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contrasenia_table_alter_docente_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numeroIdentificacion',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
