# Generated by Django 5.2.6 on 2025-09-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contrasenia_table_alter_docente_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numeroIdentificacion',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de Identificación'),
        ),
    ]
