# Generated by Django 5.2.6 on 2025-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_idusuario_facultad_idfacultad'),
        ('users', '0002_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='secretaria',
            constraint=models.UniqueConstraint(fields=('facultad',), name='unique_secretaria_por_facultad'),
        ),
    ]
