# Generated by Django 5.2.5 on 2025-11-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_secretaria_unique_secretaria_por_facultad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrasenia',
            old_name='fechaCambio',
            new_name='fecha_cambio',
        ),
        migrations.RenameField(
            model_name='contrasenia',
            old_name='idContrasenia',
            new_name='id_contrasenia',
        ),
        migrations.RenameField(
            model_name='contrasenia',
            old_name='idUsuario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='unidadAcademica',
            new_name='unidad_academica',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='idUsuario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numeroIdentificacion',
            new_name='numero_identificacion',
        ),
    ]
