# Generated by Django 5.2.6 on 2025-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_numeroidentificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numeroIdentificacion',
            field=models.CharField(default=4, max_length=10, unique=True, verbose_name='Número de Identificación'),
            preserve_default=False,
        ),
    ]
