# Generated by Django 5.2.6 on 2025-09-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
