# Generated by Django 5.2.6 on 2025-09-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('idUsuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'facultad',
                'verbose_name_plural': 'facultades',
                'db_table': 'facultad',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='numeroIdentificacion',
            field=models.CharField(default=1109666938, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('idPrograma', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='authentication.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo_estudiante', models.CharField(max_length=7, unique=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='authentication.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secretaria', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretarias', to='authentication.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('idUnidadAcademica', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_academicas', to='authentication.facultad')),
            ],
            options={
                'verbose_name': 'unidad_academica',
                'verbose_name_plural': 'unidades_academicas',
                'db_table': 'unidad_academica',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='docente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unidadAcademica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='authentication.unidadacademica')),
            ],
        ),
    ]
