# Generated by Django 5.2.6 on 2025-09-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_facultad_usuario_numeroidentificacion_programa_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facultad',
            table='authentication_facultad',
        ),
        migrations.AlterModelTable(
            name='unidadacademica',
            table='authentication_unidad_academica',
        ),
    ]
