# Generated by Django 5.2.6 on 2025-09-17 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_create_default_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasenia',
            fields=[
                ('idContrasenia', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCambio', models.DateTimeField(auto_now_add=True)),
                ('clave', models.CharField(max_length=128)),
                ('es_activa', models.BooleanField(default=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrasenias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
